#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  exec pavucontrol &
# Scroll up
elif [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  amixer -q sset Master 5%+
# Scroll down
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
  amixer -q sset Master 5%-
fi

VOLUME_ON=""
VOLUME_OFF=""
VOLUME_MUTE=""

statusLine=$(amixer get Master | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
  if [[ "${volume}" == "0" ]]; then
    echo "${VOLUME_OFF}"
    echo "${VOLUME_OFF}"
    echo ""
    exit 33
  else  
    echo "$TEST ${VOLUME_ON} ${volume}%"
    echo "${VOLUME_ON} ${volume}%"
    echo ""
  fi
else
  echo "${VOLUME_MUTE}"
  echo "${VOLUME_MUTE}"
  echo ""
  exit 33
fi
