#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

BATTERY_CHARGING=⚡
BATTERY_FULL=""
BATTERY_THREE_QUARTERS=""
BATTERY_HALF=""
BATTERY_QUARTER=""
BATTERY_EMPTY=""
BATTERY_ICON=""

URGENT_VALUE=30

if [[ "${BATTERY_POWER}" -gt 75 ]]; then
  BATTERY_ICON="${BATTERY_FULL}"
elif [[ "${BATTERY_POWER}" -le 75 && "${BATTERY_POWER}" -gt 50 ]]; then
  BATTERY_ICON="${BATTERY_THREE_QUARTERS}"
elif [[ "${BATTERY_POWER}" -le 50 && "${BATTERY_POWER}" -gt 25 ]]; then
  BATTERY_ICON="${BATTERY_HALF}"
elif [[ "${BATTERY_POWER}" -le 25 && "${BATTERY_POWER}" -gt 5 ]]; then
  BATTERY_ICON="${BATTERY_QUARTER}"
elif [[ "${BATTERY_POWER}" -le 5 ]]; then
  BATTERY_ICON="${BATTERY_EMTPY}"
fi

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  echo "${BATTERY_CHARGING} ${BATTERY_POWER}%+"
  echo "${BATTERY_CHARGING} ${BATTERY_POWER}%+"
  echo ""
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
  echo "${BATTERY_ICON} ${BATTERY_POWER}%-"
  echo "${BATTERY_ICON} ${BATTERY_POWER}%-"
  echo ""
else
  echo "${BATTERY_ICON} ${BATTERY_POWER}%"
  echo "${BATTERY_ICON} ${BATTERY_POWER}%"
  echo ""
fi

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
