#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  exec i3-sensible-terminal -e htop &
fi

URGENT_VALUE=100
CPU_VALUE="${BLOCK_INSTANCE}"

LOAD=$(cat /proc/loadavg | awk -F ' ' '{print $1}')
if [[ "${LOAD}" != "" ]]; then
  LOAD_PERC=$(echo "scale=0; ${LOAD} * 100 / ${CPU_VALUE}" | bc -l)
  LOAD_PERC=${LOAD_PERC%.*}

  echo "${LOAD}"
  echo "${LOAD}"
  echo ""

  if [[ "${LOAD_PERC}" -ge "${URGENT_VALUE}" ]]; then
    exit 33
  fi
fi
