#!/bin/bash

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
	exec i3-sensible-terminal -e nmtui &
fi

SSID_NAME=$(nmcli -t -f ACTIVE,SSID device wifi | egrep '^yes' | cut -d ":" -f 2)
device="${BLOCK_INSTANCE:-wlan0}"
status=$(cat /sys/class/net/${device}/operstate)

GOOD_SIGNAL=90
FAIR_SIGNAL=50
URGENT_SIGNAL=20

if [[ "${status}" == "up" ]]; then
  if [[ -d "/sys/class/net/${device}/wireless" ]]; then
    quality=$(grep ${device} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    echo "${quality}% ${SSID_NAME}"
    echo "${quality}%"

    if [[ "${quality}" -ge "${GOOD_SIGNAL}" ]]; then
    	echo "#C3E88D\n"
    elif [[ "${quality}" -lt "${GOOD_SIGNAL}" && "${quality}" -ge "${FAIR_SIGNAL}" ]]; then
	echo "#82AAFF\n"
    elif [[ "${quality}" -lt "${FAIR_SIGNAL}" && "${quality}" -ge "${URGEN_SIGNAL}" ]]; then
	echo "#FFCB6B\n"
    elif [[ "${quality}" -lt "${URGENT_VALUE}" ]]; then
      exit 33
    fi
  else
    echo "on"
    echo "on"
    echo ""
  fi
fi
