#!/usr/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
	exec octopi
fi

PACMAN_COUNT=$(pacman -Qu | wc -l)
YAOURT_COUNT=$(yaourt -Qu --aur | wc -l)

# Updates available for pacman
if [[ "${PACMAN_COUNT}" -gt 0 ]]; then
	echo "${PACMAN_COUNT}" 
	echo "" 		
	echo "#F07178\n"
# Updates available for AUR
elif [[ "${YAOURT_COUNT}" -gt 0 ]]; then
	echo "${YAOURT_COUNT}"
	echo ""
	echo "#FFCB6B\n"
# Everything up to date.
elif [[ "${PACMAN_COUNT}" -eq 0 ]]; then
	echo "${PACMAN_COUNT}"
	echo ""
	echo "#C3E88D\n"
fi
