#!/bin/bash
# Based on https://openweathermap.org/current

API_KEY="4300aaf3e482f76c3ad5bd9253ab1d67"

# Check on http://openweathermap.org/find
CITY_ID="${BLOCK_INSTANCE}"

URGENT_LOWER=32
URGENT_HIGHER=90

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""

UNIT="℉"

WEATHER_URL="https://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=imperial"

WEATHER_INFO=$(wget -qO - "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep  'main')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')

if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
  echo "${ICON_SNOW} ${WEATHER_TEMP}${UNIT}"
  echo "${ICON_SNOW} ${WEATHER_TEMP}${UNIT}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
  echo "${ICON_RAINY} ${WEATHER_TEMP}${UNIT}"
  echo "${ICON_RAINY} ${WEATHER_TEMP}${UNIT}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${UNIT}"
  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${UNIT}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
  echo "${ICON_SUNNY} ${WEATHER_TEMP}${UNIT}"
  echo "${ICON_SUNNY} ${WEATHER_TEMP}${UNIT}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
  echo "${ICON_FOG} ${WEATHER_TEMP}${UNIT}"
  echo "${ICON_FOG} ${WEATHER_TEMP}${UNIT}"
  echo ""
else
  echo "${WEATHER_MAIN} ${WEATHER_TEMP}${UNIT}"
  echo "${WEATHER_MAIN} ${WEATHER_TEMP}${UNIT}"
  echo ""
fi

if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]]; then
  echo "#82AAFF\n"
elif [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi
